### PR TITLE
Add 6.1

### PR DESCRIPTION
**Pull request by okliwia**

### CODE REVIEW

**Comment by Aellai** [comment]
Try using **text** and/or __text__ for bold text
*text* and/or _text_ for italics :)

**Review by w-szwarc — CHANGES_REQUESTED** [review]
Text is great but you used commands from LaTeX

**Review by Aellai — CHANGES_REQUESTED** [review]
Try using ** text ** for bold
and * text * for italics. Without spaces of course :)

**Review by Aellai — APPROVED** [review]
very nice:)

**Review by w-szwarc — APPROVED** [review]
Great

**Pull request merged**
